// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BowlingGame.Specs
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BowlingScoreTrackingWithStrikesAndSparesFeature : object, Xunit.IClassFixture<BowlingScoreTrackingWithStrikesAndSparesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BowlingScore.feature"
#line hidden
        
        public BowlingScoreTrackingWithStrikesAndSparesFeature(BowlingScoreTrackingWithStrikesAndSparesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "Bowling score tracking with strikes and spares", "  As a player\r\n  I want to keep track of scores for a bowling game with up to 10 " +
                    "players, including strikes and spares\r\n  So that we can determine the correct wi" +
                    "nner", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Player rolls a strike")]
        [Xunit.TraitAttribute("FeatureTitle", "Bowling score tracking with strikes and spares")]
        [Xunit.TraitAttribute("Description", "Player rolls a strike")]
        public async System.Threading.Tasks.Task PlayerRollsAStrike()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Player rolls a strike", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("a new bowling game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
      await testRunner.AndAsync("a player named \"Eve\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.WhenAsync("Eve records a score of 10 for frame 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
      await testRunner.AndAsync("Eve records a score of 3 for frame 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
      await testRunner.AndAsync("Eve records a score of 4 for frame 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.ThenAsync("Eve\'s total score should be 24", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Player rolls a spare")]
        [Xunit.TraitAttribute("FeatureTitle", "Bowling score tracking with strikes and spares")]
        [Xunit.TraitAttribute("Description", "Player rolls a spare")]
        public async System.Threading.Tasks.Task PlayerRollsASpare()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Player rolls a spare", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("a new bowling game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
      await testRunner.AndAsync("a player named \"Frank\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.WhenAsync("Frank records a score of 7 for frame 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
      await testRunner.AndAsync("Frank records a score of 3 for frame 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
      await testRunner.AndAsync("Frank records a score of 4 for frame 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.ThenAsync("Frank\'s total score should be 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Player scores across 10 frames")]
        [Xunit.TraitAttribute("FeatureTitle", "Bowling score tracking with strikes and spares")]
        [Xunit.TraitAttribute("Description", "Player scores across 10 frames")]
        public async System.Threading.Tasks.Task PlayerScoresAcross10Frames()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Player scores across 10 frames", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
    await testRunner.GivenAsync("a new bowling game", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
      await testRunner.AndAsync("a player named \"Grace\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Frame",
                            "Roll1",
                            "Roll2"});
                table1.AddRow(new string[] {
                            "1",
                            "10",
                            "0"});
                table1.AddRow(new string[] {
                            "2",
                            "7",
                            "3"});
                table1.AddRow(new string[] {
                            "3",
                            "9",
                            "0"});
                table1.AddRow(new string[] {
                            "4",
                            "10",
                            "0"});
                table1.AddRow(new string[] {
                            "5",
                            "0",
                            "8"});
                table1.AddRow(new string[] {
                            "6",
                            "8",
                            "2"});
                table1.AddRow(new string[] {
                            "7",
                            "0",
                            "6"});
                table1.AddRow(new string[] {
                            "8",
                            "10",
                            "0"});
                table1.AddRow(new string[] {
                            "9",
                            "10",
                            "0"});
                table1.AddRow(new string[] {
                            "10",
                            "8",
                            "1"});
#line 25
    await testRunner.WhenAsync("Grace records the following scores:", ((string)(null)), table1, "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("Grace\'s total score should be 146", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BowlingScoreTrackingWithStrikesAndSparesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BowlingScoreTrackingWithStrikesAndSparesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
